import { Inter } from 'next/font/google'
import Header from './components/Header'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Rakesh Rebbavarapu',
    description: 'Generated by create next app'
}

export default function RootLayout({children}) {

    return (<html lang="en">

        <body className={'bg-[#000]'}>
            <Header/>
            <div> {children} </div>
        </body>
    </html>)
}
